language: go

go:
  - 1.6.3
  - 1.7
  - tip

addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

cache:
  directories:
  - $HOME/.glide

install:
  - glide install --strip-vendor
